services:
  colada_app:
    container_name: colada_container
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src:ro
      - ./dist:/app/dist:ro

  mongodb:
    image: mongo:3
    restart: always
    volumes:
      - mongo-db:/data/db
    env_file:
      - ./.env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./.env   

    
volumes:
  mongo-db:
